name: Create IAM User

on:
  workflow_dispatch:
    inputs:
      iam_username:
        description: 'IAM User Name'
        required: true

jobs:
  create-user:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create IAM User
        run: |
          USERNAME="${{ github.event.inputs.iam_username }}"
          echo "Creating IAM user: $AWSUSER"
          aws iam create-user --user-name "$AWSUSER"
